version: "3.8"

services:
  api:
    build:
      context: ./Core  # Caminho do Dockerfile
    container_name: java-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # Variáveis para wait-for-db
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: mydb
      DATABASE_USER: postgres
      DATABASE_PASSWORD_FILE: /run/secrets/db_password

      # Variáveis do Spring Boot
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres

    secrets:
      - db_password 
      - jwt_secret # JWT_SECRET_FILE será lido automaticamente no entrypoint.sh
    networks:
      - backend

  db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets:
      - db_password
    networks:
      - backend

secrets:
  db_password:
    file: ./secrets/db_password.txt  # Senha do banco
  jwt_secret:
    file: ./secrets/jwt_secret.txt   # Chave JWT

volumes:
  db_data:

networks:
  backend:
